### ISSUE TITLE
用自己的数据跑loss变nan

### ISSUE THREAD

**Issue by laigood** [chenjiyan2001/Paddle-DeepRecommender#2]
尝试用自己的业务数据来跑，uid约200万，itemid约2万，评分为1-10数字，用原config_bigdata.yaml参数跑很快就出现了loss变成nan，把学习率调成0.001，在epoch2时也出现了nan，hyper_parameters里除了降低学习率，还有没有其它方法避免出现nan?

**Comment by chenjiyan2001** [comment]
Hi @laigood . 
如果你使用的损失函数和优化器和本仓库一致, 一个可能产生nan的地方是计算loss时`num_ratings`值恰好为0:
```python
def create_loss(self, inputs, targets):
        mask = paddle.where(targets != 0, paddle.ones(targets.shape),
                            paddle.zeros(targets.shape))
        num_ratings = paddle.sum(mask)
        loss = nn.functional.mse_loss(inputs * mask, targets, reduction='sum') / num_ratings
        return loss
```
模型本身运算过程只涉及乘法和加法, 激活函数ReLU也是线性运算, 应该不是网络本身带来的问题. 如果怀疑是网络的问题, 使用的优化器Momentum有参数grad_clip, 可以查阅[Paddle文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/Momentum_cn.html)进行设置, 避免梯度爆炸产生的nan.

我的经验不足, 可能没法帮助你顺利处理. 如果问题还是无法解决, 可以前往[PaddleRec](https://github.com/PaddlePaddle/PaddleRec)提issue(最好带上训练日志和相关信息), 会有专业人员帮忙解决,

祝顺利.
